name=jct_dn24f08
version=1.1.0
author=Costello Technical <youtube@costellotechnical.com>
maintainer=Costello Technical <youtube@costellotechnical.com>
sentence=The function of this library is to give the use full control of the dn24f08 expansion board.
paragraph=This library allows you to control the digital inputs, outputs and analog inputs of the dn24f08. It also gives some examples of how one might go about controlling the module via the RS485 chip.
category=Industrial Arduino Nano.
url=http://example.com/
architectures=*
depends=*